# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"H\n\x12\x43\x61lculationRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x02\x12\x0c\n\x04num2\x18\x02 \x01(\x02\x12\x16\n\x02op\x18\x03 \x01(\x0e\x32\n.Operation\"%\n\x13\x43\x61lculationResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02*;\n\tOperation\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\t\n\x05MINUS\x10\x01\x12\x0c\n\x08MULTIPLY\x10\x02\x12\x0c\n\x08\x44IVISION\x10\x03\x32\x44\n\nCalculator\x12\x36\n\tcalculate\x12\x13.CalculationRequest\x1a\x14.CalculationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERATION']._serialized_start=133
  _globals['_OPERATION']._serialized_end=192
  _globals['_CALCULATIONREQUEST']._serialized_start=20
  _globals['_CALCULATIONREQUEST']._serialized_end=92
  _globals['_CALCULATIONRESPONSE']._serialized_start=94
  _globals['_CALCULATIONRESPONSE']._serialized_end=131
  _globals['_CALCULATOR']._serialized_start=194
  _globals['_CALCULATOR']._serialized_end=262
# @@protoc_insertion_point(module_scope)
